/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as SeRouteImport } from './routes/se'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DatapolicyRouteImport } from './routes/datapolicy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as VerifyCodeRouteImport } from './routes/verify/$code'
import { Route as EnTeamRouteImport } from './routes/en/team'
import { Route as EnRulesRouteImport } from './routes/en/rules'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminGuidesRouteImport } from './routes/admin/guides'
import { Route as AdminCmsRouteImport } from './routes/admin/cms'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicTeamRouteImport } from './routes/_public/team'
import { Route as PublicRulesRouteImport } from './routes/_public/rules'
import { Route as ProtectedExampleProtectedRouteRouteImport } from './routes/_protected/example-protected-route'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as EnBlogsIndexRouteImport } from './routes/en/blogs/index'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin/tickets/index'
import { Route as PublicDatapolicyIndexRouteImport } from './routes/_public/datapolicy/index'
import { Route as AdminTicketsTypesRouteImport } from './routes/admin/tickets/types'
import { Route as AdminTicketsScanRouteImport } from './routes/admin/tickets/scan'
import { Route as AdminTicketsNewRouteImport } from './routes/admin/tickets/new'
import { Route as AdminTicketsEventsRouteImport } from './routes/admin/tickets/events'
import { Route as AdminTicketsCompaniesRouteImport } from './routes/admin/tickets/companies'
import { Route as AdminEditIdRouteImport } from './routes/admin/edit/$id'
import { Route as AdminCmsTeamRouteImport } from './routes/admin/cms/team'
import { Route as AdminCmsSettingsRouteImport } from './routes/admin/cms/settings'
import { Route as AdminCmsSectionsRouteImport } from './routes/admin/cms/sections'
import { Route as AdminCmsPagesRouteImport } from './routes/admin/cms/pages'
import { Route as AdminCmsNavigationRouteImport } from './routes/admin/cms/navigation'
import { Route as AdminCmsHeroRouteImport } from './routes/admin/cms/hero'
import { Route as PublicDatapolicySeRouteImport } from './routes/_public/datapolicy/se'
import { Route as PublicBiljettCodeRouteImport } from './routes/_public/biljett/$code'

const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const SeRoute = SeRouteImport.update({
  id: '/se',
  path: '/se',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DatapolicyRoute = DatapolicyRouteImport.update({
  id: '/datapolicy',
  path: '/datapolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTeamRoute = EnTeamRouteImport.update({
  id: '/en/team',
  path: '/en/team',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRulesRoute = EnRulesRouteImport.update({
  id: '/en/rules',
  path: '/en/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamRoute = PublicTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRulesRoute = PublicRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedExampleProtectedRouteRoute =
  ProtectedExampleProtectedRouteRouteImport.update({
    id: '/example-protected-route',
    path: '/example-protected-route',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogsIndexRoute = EnBlogsIndexRouteImport.update({
  id: '/en/blogs/',
  path: '/en/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicDatapolicyIndexRoute = PublicDatapolicyIndexRouteImport.update({
  id: '/datapolicy/',
  path: '/datapolicy/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminTicketsTypesRoute = AdminTicketsTypesRouteImport.update({
  id: '/tickets/types',
  path: '/tickets/types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsScanRoute = AdminTicketsScanRouteImport.update({
  id: '/tickets/scan',
  path: '/tickets/scan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsNewRoute = AdminTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsEventsRoute = AdminTicketsEventsRouteImport.update({
  id: '/tickets/events',
  path: '/tickets/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsCompaniesRoute = AdminTicketsCompaniesRouteImport.update({
  id: '/tickets/companies',
  path: '/tickets/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsTeamRoute = AdminCmsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsSettingsRoute = AdminCmsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsSectionsRoute = AdminCmsSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsPagesRoute = AdminCmsPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsNavigationRoute = AdminCmsNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsHeroRoute = AdminCmsHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminCmsRoute,
} as any)
const PublicDatapolicySeRoute = PublicDatapolicySeRouteImport.update({
  id: '/datapolicy/se',
  path: '/datapolicy/se',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBiljettCodeRoute = PublicBiljettCodeRouteImport.update({
  id: '/biljett/$code',
  path: '/biljett/$code',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/datapolicy': typeof DatapolicyRoute
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/sponsor': typeof SponsorRoute
  '/hello': typeof ApiHelloRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/rules': typeof PublicRulesRoute
  '/team': typeof PublicTeamRoute
  '/terms': typeof PublicTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/en/rules': typeof EnRulesRoute
  '/en/team': typeof EnTeamRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/en/': typeof EnIndexRoute
  '/biljett/$code': typeof PublicBiljettCodeRoute
  '/datapolicy/se': typeof PublicDatapolicySeRoute
  '/admin/cms/hero': typeof AdminCmsHeroRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/pages': typeof AdminCmsPagesRoute
  '/admin/cms/sections': typeof AdminCmsSectionsRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cms/team': typeof AdminCmsTeamRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/tickets/companies': typeof AdminTicketsCompaniesRoute
  '/admin/tickets/events': typeof AdminTicketsEventsRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/tickets/scan': typeof AdminTicketsScanRoute
  '/admin/tickets/types': typeof AdminTicketsTypesRoute
  '/datapolicy/': typeof PublicDatapolicyIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/en/blogs/': typeof EnBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/datapolicy': typeof PublicDatapolicyIndexRoute
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/sponsor': typeof SponsorRoute
  '/hello': typeof ApiHelloRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/rules': typeof PublicRulesRoute
  '/team': typeof PublicTeamRoute
  '/terms': typeof PublicTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/en/rules': typeof EnRulesRoute
  '/en/team': typeof EnTeamRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/en': typeof EnIndexRoute
  '/biljett/$code': typeof PublicBiljettCodeRoute
  '/datapolicy/se': typeof PublicDatapolicySeRoute
  '/admin/cms/hero': typeof AdminCmsHeroRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/pages': typeof AdminCmsPagesRoute
  '/admin/cms/sections': typeof AdminCmsSectionsRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cms/team': typeof AdminCmsTeamRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/tickets/companies': typeof AdminTicketsCompaniesRoute
  '/admin/tickets/events': typeof AdminTicketsEventsRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/tickets/scan': typeof AdminTicketsScanRoute
  '/admin/tickets/types': typeof AdminTicketsTypesRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
  '/en/blogs': typeof EnBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/datapolicy': typeof DatapolicyRoute
  '/login': typeof LoginRoute
  '/se': typeof SeRoute
  '/sponsor': typeof SponsorRoute
  '/_api/hello': typeof ApiHelloRoute
  '/_protected/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/_public/rules': typeof PublicRulesRoute
  '/_public/team': typeof PublicTeamRoute
  '/_public/terms': typeof PublicTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/en/rules': typeof EnRulesRoute
  '/en/team': typeof EnTeamRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/en/': typeof EnIndexRoute
  '/_public/biljett/$code': typeof PublicBiljettCodeRoute
  '/_public/datapolicy/se': typeof PublicDatapolicySeRoute
  '/admin/cms/hero': typeof AdminCmsHeroRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/pages': typeof AdminCmsPagesRoute
  '/admin/cms/sections': typeof AdminCmsSectionsRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cms/team': typeof AdminCmsTeamRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/tickets/companies': typeof AdminTicketsCompaniesRoute
  '/admin/tickets/events': typeof AdminTicketsEventsRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/tickets/scan': typeof AdminTicketsScanRoute
  '/admin/tickets/types': typeof AdminTicketsTypesRoute
  '/_public/datapolicy/': typeof PublicDatapolicyIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/en/blogs/': typeof EnBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/datapolicy'
    | '/login'
    | '/se'
    | '/sponsor'
    | '/hello'
    | '/example-protected-route'
    | '/rules'
    | '/team'
    | '/terms'
    | '/admin/analytics'
    | '/admin/cms'
    | '/admin/guides'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/new'
    | '/admin/posts'
    | '/admin/users'
    | '/blogs/$slug'
    | '/en/rules'
    | '/en/team'
    | '/verify/$code'
    | '/admin/'
    | '/blogs/'
    | '/en/'
    | '/biljett/$code'
    | '/datapolicy/se'
    | '/admin/cms/hero'
    | '/admin/cms/navigation'
    | '/admin/cms/pages'
    | '/admin/cms/sections'
    | '/admin/cms/settings'
    | '/admin/cms/team'
    | '/admin/edit/$id'
    | '/admin/tickets/companies'
    | '/admin/tickets/events'
    | '/admin/tickets/new'
    | '/admin/tickets/scan'
    | '/admin/tickets/types'
    | '/datapolicy/'
    | '/admin/tickets/'
    | '/en/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datapolicy'
    | '/login'
    | '/se'
    | '/sponsor'
    | '/hello'
    | '/example-protected-route'
    | '/rules'
    | '/team'
    | '/terms'
    | '/admin/analytics'
    | '/admin/cms'
    | '/admin/guides'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/new'
    | '/admin/posts'
    | '/admin/users'
    | '/blogs/$slug'
    | '/en/rules'
    | '/en/team'
    | '/verify/$code'
    | '/admin'
    | '/blogs'
    | '/en'
    | '/biljett/$code'
    | '/datapolicy/se'
    | '/admin/cms/hero'
    | '/admin/cms/navigation'
    | '/admin/cms/pages'
    | '/admin/cms/sections'
    | '/admin/cms/settings'
    | '/admin/cms/team'
    | '/admin/edit/$id'
    | '/admin/tickets/companies'
    | '/admin/tickets/events'
    | '/admin/tickets/new'
    | '/admin/tickets/scan'
    | '/admin/tickets/types'
    | '/admin/tickets'
    | '/en/blogs'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/admin'
    | '/datapolicy'
    | '/login'
    | '/se'
    | '/sponsor'
    | '/_api/hello'
    | '/_protected/example-protected-route'
    | '/_public/rules'
    | '/_public/team'
    | '/_public/terms'
    | '/admin/analytics'
    | '/admin/cms'
    | '/admin/guides'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/new'
    | '/admin/posts'
    | '/admin/users'
    | '/blogs/$slug'
    | '/en/rules'
    | '/en/team'
    | '/verify/$code'
    | '/_public/'
    | '/admin/'
    | '/blogs/'
    | '/en/'
    | '/_public/biljett/$code'
    | '/_public/datapolicy/se'
    | '/admin/cms/hero'
    | '/admin/cms/navigation'
    | '/admin/cms/pages'
    | '/admin/cms/sections'
    | '/admin/cms/settings'
    | '/admin/cms/team'
    | '/admin/edit/$id'
    | '/admin/tickets/companies'
    | '/admin/tickets/events'
    | '/admin/tickets/new'
    | '/admin/tickets/scan'
    | '/admin/tickets/types'
    | '/_public/datapolicy/'
    | '/admin/tickets/'
    | '/en/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DatapolicyRoute: typeof DatapolicyRoute
  LoginRoute: typeof LoginRoute
  SeRoute: typeof SeRoute
  SponsorRoute: typeof SponsorRoute
  ApiHelloRoute: typeof ApiHelloRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  EnRulesRoute: typeof EnRulesRoute
  EnTeamRoute: typeof EnTeamRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EnBlogsIndexRoute: typeof EnBlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/se': {
      id: '/se'
      path: '/se'
      fullPath: '/se'
      preLoaderRoute: typeof SeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datapolicy': {
      id: '/datapolicy'
      path: '/datapolicy'
      fullPath: '/datapolicy'
      preLoaderRoute: typeof DatapolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/team': {
      id: '/en/team'
      path: '/en/team'
      fullPath: '/en/team'
      preLoaderRoute: typeof EnTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/rules': {
      id: '/en/rules'
      path: '/en/rules'
      fullPath: '/en/rules'
      preLoaderRoute: typeof EnRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team': {
      id: '/_public/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PublicTeamRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rules': {
      id: '/_public/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof PublicRulesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/example-protected-route': {
      id: '/_protected/example-protected-route'
      path: '/example-protected-route'
      fullPath: '/example-protected-route'
      preLoaderRoute: typeof ProtectedExampleProtectedRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blogs/': {
      id: '/en/blogs/'
      path: '/en/blogs'
      fullPath: '/en/blogs/'
      preLoaderRoute: typeof EnBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/datapolicy/': {
      id: '/_public/datapolicy/'
      path: '/datapolicy'
      fullPath: '/datapolicy/'
      preLoaderRoute: typeof PublicDatapolicyIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/tickets/types': {
      id: '/admin/tickets/types'
      path: '/tickets/types'
      fullPath: '/admin/tickets/types'
      preLoaderRoute: typeof AdminTicketsTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/scan': {
      id: '/admin/tickets/scan'
      path: '/tickets/scan'
      fullPath: '/admin/tickets/scan'
      preLoaderRoute: typeof AdminTicketsScanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/new': {
      id: '/admin/tickets/new'
      path: '/tickets/new'
      fullPath: '/admin/tickets/new'
      preLoaderRoute: typeof AdminTicketsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/events': {
      id: '/admin/tickets/events'
      path: '/tickets/events'
      fullPath: '/admin/tickets/events'
      preLoaderRoute: typeof AdminTicketsEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/companies': {
      id: '/admin/tickets/companies'
      path: '/tickets/companies'
      fullPath: '/admin/tickets/companies'
      preLoaderRoute: typeof AdminTicketsCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/team': {
      id: '/admin/cms/team'
      path: '/team'
      fullPath: '/admin/cms/team'
      preLoaderRoute: typeof AdminCmsTeamRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/settings': {
      id: '/admin/cms/settings'
      path: '/settings'
      fullPath: '/admin/cms/settings'
      preLoaderRoute: typeof AdminCmsSettingsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/sections': {
      id: '/admin/cms/sections'
      path: '/sections'
      fullPath: '/admin/cms/sections'
      preLoaderRoute: typeof AdminCmsSectionsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/pages': {
      id: '/admin/cms/pages'
      path: '/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AdminCmsPagesRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/navigation': {
      id: '/admin/cms/navigation'
      path: '/navigation'
      fullPath: '/admin/cms/navigation'
      preLoaderRoute: typeof AdminCmsNavigationRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/hero': {
      id: '/admin/cms/hero'
      path: '/hero'
      fullPath: '/admin/cms/hero'
      preLoaderRoute: typeof AdminCmsHeroRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/_public/datapolicy/se': {
      id: '/_public/datapolicy/se'
      path: '/datapolicy/se'
      fullPath: '/datapolicy/se'
      preLoaderRoute: typeof PublicDatapolicySeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/biljett/$code': {
      id: '/_public/biljett/$code'
      path: '/biljett/$code'
      fullPath: '/biljett/$code'
      preLoaderRoute: typeof PublicBiljettCodeRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedExampleProtectedRouteRoute: typeof ProtectedExampleProtectedRouteRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedExampleProtectedRouteRoute: ProtectedExampleProtectedRouteRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicRulesRoute: typeof PublicRulesRoute
  PublicTeamRoute: typeof PublicTeamRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBiljettCodeRoute: typeof PublicBiljettCodeRoute
  PublicDatapolicySeRoute: typeof PublicDatapolicySeRoute
  PublicDatapolicyIndexRoute: typeof PublicDatapolicyIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicRulesRoute: PublicRulesRoute,
  PublicTeamRoute: PublicTeamRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBiljettCodeRoute: PublicBiljettCodeRoute,
  PublicDatapolicySeRoute: PublicDatapolicySeRoute,
  PublicDatapolicyIndexRoute: PublicDatapolicyIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminCmsRouteChildren {
  AdminCmsHeroRoute: typeof AdminCmsHeroRoute
  AdminCmsNavigationRoute: typeof AdminCmsNavigationRoute
  AdminCmsPagesRoute: typeof AdminCmsPagesRoute
  AdminCmsSectionsRoute: typeof AdminCmsSectionsRoute
  AdminCmsSettingsRoute: typeof AdminCmsSettingsRoute
  AdminCmsTeamRoute: typeof AdminCmsTeamRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsHeroRoute: AdminCmsHeroRoute,
  AdminCmsNavigationRoute: AdminCmsNavigationRoute,
  AdminCmsPagesRoute: AdminCmsPagesRoute,
  AdminCmsSectionsRoute: AdminCmsSectionsRoute,
  AdminCmsSettingsRoute: AdminCmsSettingsRoute,
  AdminCmsTeamRoute: AdminCmsTeamRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminGuidesRoute: typeof AdminGuidesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
  AdminTicketsCompaniesRoute: typeof AdminTicketsCompaniesRoute
  AdminTicketsEventsRoute: typeof AdminTicketsEventsRoute
  AdminTicketsNewRoute: typeof AdminTicketsNewRoute
  AdminTicketsScanRoute: typeof AdminTicketsScanRoute
  AdminTicketsTypesRoute: typeof AdminTicketsTypesRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminGuidesRoute: AdminGuidesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNewRoute: AdminNewRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditIdRoute: AdminEditIdRoute,
  AdminTicketsCompaniesRoute: AdminTicketsCompaniesRoute,
  AdminTicketsEventsRoute: AdminTicketsEventsRoute,
  AdminTicketsNewRoute: AdminTicketsNewRoute,
  AdminTicketsScanRoute: AdminTicketsScanRoute,
  AdminTicketsTypesRoute: AdminTicketsTypesRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DatapolicyRoute: DatapolicyRoute,
  LoginRoute: LoginRoute,
  SeRoute: SeRoute,
  SponsorRoute: SponsorRoute,
  ApiHelloRoute: ApiHelloRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  EnRulesRoute: EnRulesRoute,
  EnTeamRoute: EnTeamRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EnBlogsIndexRoute: EnBlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
